export const PREFIX = '@@experium-modules/';

export const GET_DICTIONARY = PREFIX + 'GET_DICTIONARY';
export const DOCUMENT_UPDATE = PREFIX + 'DOCUMENT_UPDATE';
export const DOCUMENT_REMOVE = PREFIX + 'DOCUMENT_REMOVE';
export const DOCUMENT_UPLOAD = PREFIX + 'DOCUMENT_UPLOAD';
export const LOGIN = PREFIX + 'LOGIN';
export const SEND_RECOVERY_EMAIL = PREFIX + 'SEND_RECOVERY_EMAIL';
export const PASSWORD_CONFIRM = PREFIX + 'PASSWORD_CONFIRM';
